export const APP_NAME = 'CTAL AI'
export const APP_DESCRIPTION = 'AI-Powered Operating System for Growth'
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://ctalai.vercel.app'

export const COLORS = {
  primary: '#3452ff',
  primaryLight: '#5a7aff',
  primaryDark: '#2341cc',
  secondary: '#ff1053',
  secondaryLight: '#ff4d7a',
  secondaryDark: '#cc0d42',
  background: '#0a0a0f',
  surface: '#12121a',
  surfaceLight: '#1a1a25',
  text: '#ffffff',
  textMuted: '#6b7280',
  success: '#10b981',
  warning: '#f59e0b',
  error: '#ef4444',
}

export const FEATURES = [
  {
    id: 'lead-generation',
    number: '02',
    title: 'Lead Generation & Marketing',
    description: 'Automated lead capture, scoring, segmentation and qualification across all channels.',
    icon: 'Megaphone',
    category: 'marketing',
  },
  {
    id: 'sales',
    number: '03',
    title: 'Sales & Conversion',
    description: 'Pipeline management, automated follow-ups and opportunity detection.',
    icon: 'TrendingUp',
    category: 'sales',
  },
  {
    id: 'crm',
    number: '04',
    title: 'Customer Relationship Management',
    description: '360-degree customer profiles and single source of truth.',
    icon: 'Users',
    category: 'crm',
  },
  {
    id: 'onboarding',
    number: '05',
    title: 'Customer Onboarding',
    description: 'Automated welcome sequences, forms and orientation workflows.',
    icon: 'UserPlus',
    category: 'crm',
  },
  {
    id: 'training',
    number: '06',
    title: 'Training Programme Management',
    description: 'Cohort management, attendance tracking and certificate workflows.',
    icon: 'GraduationCap',
    category: 'learning',
  },
  {
    id: 'support',
    number: '07',
    title: 'Live Q&A & Customer Support',
    description: 'Automated FAQ responses, ticketing and escalation workflows.',
    icon: 'Headphones',
    category: 'support',
  },
  {
    id: 'coaching',
    number: '08',
    title: 'Coaching & Mentoring',
    description: 'Client matching, scheduling, action plans and progress tracking.',
    icon: 'Target',
    category: 'learning',
  },
  {
    id: 'alumni',
    number: '09',
    title: 'Alumni & Community',
    description: 'Alumni network, opportunities and AI-powered skill matching.',
    icon: 'Heart',
    category: 'community',
  },
  {
    id: 'retention',
    number: '10',
    title: 'Customer Retention',
    description: 'Re-engagement campaigns, churn alerts and lifetime value tracking.',
    icon: 'RefreshCw',
    category: 'crm',
  },
  {
    id: 'feedback',
    number: '11',
    title: 'Feedback & Satisfaction',
    description: 'Surveys, sentiment analysis and performance monitoring.',
    icon: 'MessageSquare',
    category: 'analytics',
  },
  {
    id: 'content',
    number: '12',
    title: 'Content & Knowledge',
    description: 'Central knowledge base and AI-powered content repurposing.',
    icon: 'FileText',
    category: 'operations',
  },
  {
    id: 'curriculum',
    number: '13',
    title: 'Course Development',
    description: 'Training needs assessment, curriculum design and QA workflows.',
    icon: 'BookOpen',
    category: 'learning',
  },
  {
    id: 'finance',
    number: '14',
    title: 'Finance & Payments',
    description: 'Invoicing, payment tracking, revenue analytics and cash flow alerts.',
    icon: 'DollarSign',
    category: 'finance',
  },
  {
    id: 'hr',
    number: '15',
    title: 'HR & Staff Management',
    description: 'Recruitment, onboarding, KPIs and performance tracking.',
    icon: 'Briefcase',
    category: 'people',
  },
  {
    id: 'projects',
    number: '16',
    title: 'Project Management',
    description: 'Task assignment, milestones, risks and budget tracking.',
    icon: 'FolderKanban',
    category: 'operations',
  },
  {
    id: 'ceo',
    number: '17',
    title: 'CEO & Executive Assistant',
    description: 'Daily briefings, meeting prep and executive dashboards.',
    icon: 'Crown',
    category: 'intelligence',
  },
  {
    id: 'bi',
    number: '18',
    title: 'Business Intelligence',
    description: 'Executive dashboards, trend detection and KPI alerts.',
    icon: 'BarChart3',
    category: 'analytics',
  },
  {
    id: 'partnerships',
    number: '19',
    title: 'Partnerships',
    description: 'Partner database, MoU tracking and performance reporting.',
    icon: 'Handshake',
    category: 'growth',
  },
  {
    id: 'sops',
    number: '20',
    title: 'SOPs & Documents',
    description: 'Central repository with AI-powered retrieval and version control.',
    icon: 'FileCheck',
    category: 'operations',
  },
  {
    id: 'analytics',
    number: '21',
    title: 'Marketing Analytics',
    description: 'Channel tracking, customer insights and campaign optimisation.',
    icon: 'PieChart',
    category: 'analytics',
  },
  {
    id: 'risk',
    number: '22',
    title: 'Risk & Exception Management',
    description: 'Alerts, monitoring and automated escalation of critical issues.',
    icon: 'AlertTriangle',
    category: 'operations',
  },
]

export const AI_AGENTS = [
  {
    id: 'growth',
    name: 'Growth Agent',
    description: 'Marketing, lead generation, qualification, sales and conversion.',
    icon: 'Rocket',
    color: '#3452ff',
    capabilities: ['Lead Scoring', 'Campaign Optimization', 'Sales Forecasting', 'Conversion Tracking'],
  },
  {
    id: 'customer-success',
    name: 'Customer Success Agent',
    description: 'CRM, onboarding, support, customer experience and retention.',
    icon: 'HeartHandshake',
    color: '#ff1053',
    capabilities: ['Health Scoring', 'Churn Prediction', 'Onboarding Automation', 'Support Routing'],
  },
  {
    id: 'learning',
    name: 'Learning Agent',
    description: 'Training programmes, participant engagement, assessments and learning workflows.',
    icon: 'Brain',
    color: '#10b981',
    capabilities: ['Adaptive Learning', 'Progress Tracking', 'Content Recommendations', 'Assessment Analysis'],
  },
  {
    id: 'community',
    name: 'Community Agent',
    description: 'Alumni engagement, networking, opportunities and referrals.',
    icon: 'Globe',
    color: '#f59e0b',
    capabilities: ['Skill Matching', 'Opportunity Matching', 'Engagement Analysis', 'Referral Tracking'],
  },
  {
    id: 'operations',
    name: 'Operations Agent',
    description: 'Tasks, projects, SOPs, deadlines and operational coordination.',
    icon: 'Settings',
    color: '#8b5cf6',
    capabilities: ['Task Prioritization', 'Bottleneck Detection', 'Resource Optimization', 'SOP Compliance'],
  },
  {
    id: 'finance',
    name: 'Finance Agent',
    description: 'Payments, invoices, revenue tracking, financial alerts and reporting.',
    icon: 'Calculator',
    color: '#06b6d4',
    capabilities: ['Cash Flow Prediction', 'Invoice Automation', 'Anomaly Detection', 'Budget Optimization'],
  },
  {
    id: 'people',
    name: 'People Agent',
    description: 'Recruitment, onboarding, staff records, KPIs, performance and workload.',
    icon: 'Users',
    color: '#ec4899',
    capabilities: ['CV Screening', 'Performance Analysis', 'Workload Balancing', 'Leave Optimization'],
  },
  {
    id: 'ceo-intelligence',
    name: 'CEO Intelligence Agent',
    description: 'Executive dashboards, insights, alerts, summaries and decision support.',
    icon: 'Zap',
    color: '#f97316',
    capabilities: ['Executive Summaries', 'Decision Support', 'Trend Analysis', 'Priority Alerts'],
  },
]

export const CUSTOMER_JOURNEY = [
  { step: 1, title: 'Lead Entry', description: 'Lead enters CTAL ecosystem', icon: 'LogIn' },
  { step: 2, title: 'AI Qualification', description: 'AI qualifies and segments the lead', icon: 'Scan' },
  { step: 3, title: 'CRM Profile', description: 'CRM profile is created or updated', icon: 'UserPlus' },
  { step: 4, title: 'AI Nurturing', description: 'AI nurtures the lead and recommends next action', icon: 'Heart' },
  { step: 5, title: 'Registration', description: 'Customer registers and pays', icon: 'CreditCard' },
  { step: 6, title: 'Onboarding', description: 'Automated onboarding begins', icon: 'ClipboardCheck' },
  { step: 7, title: 'Programme Delivery', description: 'Programme delivery and engagement are monitored', icon: 'Monitor' },
  { step: 8, title: 'Human Support', description: 'Human team intervenes where high-touch support is required', icon: 'Users' },
  { step: 9, title: 'Feedback', description: 'Feedback and satisfaction data are collected', icon: 'MessageSquare' },
  { step: 10, title: 'Alumni', description: 'Customer joins the alumni/community ecosystem', icon: 'GraduationCap' },
  { step: 11, title: 'AI Recommendation', description: 'AI recommends the next relevant opportunity', icon: 'Sparkles' },
  { step: 12, title: 'Growth', description: 'Customer returns, refers others, collaborates or becomes a partner', icon: 'TrendingUp' },
]

export const NAVIGATION = {
  marketing: [
    { label: 'Home', href: '/' },
    { label: 'Features', href: '/features' },
    { label: 'AI Agents', href: '/agents' },
    { label: 'Journey', href: '/journey' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Contact', href: '/contact' },
  ],
  dashboard: [
    { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'CRM', href: '/dashboard/crm', icon: 'Users' },
    { label: 'Leads', href: '/dashboard/leads', icon: 'Target' },
    { label: 'Programmes', href: '/dashboard/programs', icon: 'GraduationCap' },
    { label: 'Coaching', href: '/dashboard/coaching', icon: 'Brain' },
    { label: 'Alumni', href: '/dashboard/alumni', icon: 'Heart' },
    { label: 'Finance', href: '/dashboard/finance', icon: 'DollarSign' },
    { label: 'HR', href: '/dashboard/hr', icon: 'Briefcase' },
    { label: 'Projects', href: '/dashboard/projects', icon: 'FolderKanban' },
    { label: 'Support', href: '/dashboard/support', icon: 'Headphones' },
    { label: 'Partners', href: '/dashboard/partners', icon: 'Handshake' },
    { label: 'Content', href: '/dashboard/content', icon: 'FileText' },
    { label: 'AI Agents', href: '/dashboard/ai', icon: 'Bot' },
    { label: 'Analytics', href: '/dashboard/analytics', icon: 'BarChart3' },
    { label: 'Settings', href: '/dashboard/settings', icon: 'Settings' },
  ],
}
