import jsPDF from 'jspdf'

interface InvoiceData {
  invoiceNumber: string
  customerName: string
  customerEmail: string
  amount: number
  description: string
  dueDate: string
  status: string
}

export function generateInvoicePDF(invoice: InvoiceData): void {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(24)
  doc.setTextColor(52, 82, 255) // Primary blue
  doc.text('CTAL AI', 20, 25)
  
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('CoreSkills Transformational Academy Limited', 20, 32)
  doc.text('hello@ctalai.com | +234 800 123 4567', 20, 38)
  
  // Invoice title
  doc.setFontSize(20)
  doc.setTextColor(0, 0, 0)
  doc.text('INVOICE', 140, 25)
  
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 140, 33)
  doc.text(`Date: ${new Date().toLocaleDateString('en-NG')}`, 140, 39)
  doc.text(`Due: ${invoice.dueDate}`, 140, 45)
  doc.text(`Status: ${invoice.status}`, 140, 51)
  
  // Bill to
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text('Bill To:', 20, 55)
  
  doc.setFontSize(10)
  doc.text(invoice.customerName, 20, 63)
  doc.text(invoice.customerEmail, 20, 69)
  
  // Line items
  doc.setFillColor(52, 82, 255)
  doc.rect(20, 80, 170, 8, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.text('Description', 22, 86)
  doc.text('Amount', 150, 86)
  
  doc.setTextColor(0, 0, 0)
  doc.text(invoice.description || 'Programme Fee', 22, 96)
  doc.text(`\u20A6${invoice.amount.toLocaleString()}`, 150, 96)
  
  // Total
  doc.setDrawColor(200, 200, 200)
  doc.line(20, 102, 190, 102)
  
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Total:', 120, 112)
  doc.text(`\u20A6${invoice.amount.toLocaleString()}`, 150, 112)
  
  // Footer
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Thank you for your business!', 20, 140)
  doc.text('This invoice was generated by CTAL AI', 20, 146)
  
  doc.save(`Invoice-${invoice.invoiceNumber}.pdf`)
}
